styles:
  templates:
    layoutRootPath: "EXT:sitepackage/Resources/Private/ContentElements/Layouts/"
    partialRootPath: "EXT:sitepackage/Resources/Private/ContentElements/Partials/"
    templateRootPath: "EXT:sitepackage/Resources/Private/ContentElements/Templates/"

page:
  pageview:
    paths: "EXT:sitepackage/Resources/Private/PageView/"

  meta:
    viewport: "width=device-width, initial-scale=1"
    robots: "index,follow"
    apple-mobile-web-app-capable: "no"
    compatible: "IE=edge"

  tracking:
    google:
      trackingID: ""
      anonymizeIp: "1"

config:
  no_cache: "1"
  removeDefaultJS: "0"
  admPanel: "1"
  prefixLocalAnchors: "all"
  sendCacheHeaders: "1"
