base: 'https://a11y-comp.ddev.site'
baseVariants:
  -
    base: 'https://a11y-comp.test'
    condition: "applicationContext == 'Development/Local'"
  -
    base: 'https://a11y-comp.test'
    condition: "applicationContext == 'Production/Local'"
  -
    base: 'https://a11y-compendium.dev'
    condition: 'applicationContext == "Production/Production"'
dependencies:
  - typo3/fluid-styled-content
  - typo3/seo-sitemap
  - private/sitepackage
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    flag: de
    languageId: 0
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
